#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'diagonalDifference' function below.
#
# The function is expected to return an INTEGER.
# The function accepts 2D_INTEGER_ARRAY arr as parameter.
#

def diagonalDifference(arr):
    # Write your code here

    def helper():
        result = 0
        for i in range(len(ar)):
            result+= ar[i][i]
        return result
    
    b=[]
    for i in arr:
        b.append(i[::-1])

    ans1 = helper(arr)
    ans2 = helper(b)

    return abs(ans1-ans2)


if __name__ == "__main__":
    # Example test
    arr = [
        [11, 2, 4],
        [4, 5, 6],
        [10, 8, -12]
    ]
    print(diagonalDifference(arr))  # Output: 15